---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="tests/test.yml -i tests/inventory"

before_install:
  - "sudo apt-get update -qq"

install:
  - "pip install ansible==1.6.2"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_AND_INVENTORY --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    sudo ufw status
    | grep -q '80/tcp\s*ALLOW'
    && (echo 'Port test: pass' && exit 0)
    || (echo 'Port test: fail' && exit 1)
  - >
    ps cax
    | grep -q 'fail2ban'
    && (echo 'Port test: pass' && exit 0)
    || (echo 'Port test: fail' && exit 1)